# Generated by Django 6.0 on 2025-12-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_supportmessage_admin_reply_supportmessage_replied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
