# Generated by Django 6.0 on 2025-12-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_support_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='custom_email_message',
            field=models.TextField(blank=True, help_text='Optional: Send a custom email to the user when saving.'),
        ),
    ]
