# Generated by Django 6.0 on 2025-12-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tracking_custom_email_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='user_location',
            field=models.CharField(blank=True, help_text='Delivery location (address or coordinates)', max_length=255),
        ),
    ]
