# Generated by Django 6.0 on 2025-12-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tracking_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='user_location',
        ),
        migrations.AddField(
            model_name='tracking',
            name='from_location',
            field=models.CharField(blank=True, help_text='Pickup location (address or coordinates)', max_length=255),
        ),
        migrations.AddField(
            model_name='tracking',
            name='to_location',
            field=models.CharField(blank=True, help_text='Delivery location (address or coordinates)', max_length=255),
        ),
    ]
