# Generated by Django 4.2.7 on 2025-12-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_tracking_user_location_tracking_from_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, help_text='Shipping/delivery address'),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admin'),
        ),
        migrations.AddField(
            model_name='order',
            name='crypto_address',
            field=models.CharField(blank=True, help_text='Admin sets crypto payment address', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='crypto_currency',
            field=models.CharField(blank=True, default='USDT', help_text='e.g., BTC, ETH, USDT', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in USD', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.TextField(blank=True, help_text='Transaction hash or proof from customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof_image',
            field=models.CharField(blank=True, help_text='URL to payment screenshot', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('payment_submitted', 'Payment Proof Submitted'), ('payment_approved', 'Payment Approved'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
